In [1]:
import numpy as np


In [2]:
ar1 = np.arange(6).reshape(2,3)
ar2 = np.arange(5,11).reshape(2,3)

print(ar1)
print(ar2)

[[0 1 2]
 [3 4 5]]
[[ 5  6  7]
 [ 8  9 10]]


In [3]:
a0 = np.concatenate((ar1,ar2),axis=0)
a0

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [4]:
a1 = np.concatenate((ar1,ar2),axis=1)
a1

array([[ 0,  1,  2,  5,  6,  7],
       [ 3,  4,  5,  8,  9, 10]])

In [5]:
an = np.concatenate((ar1,ar2))
an

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [6]:
# print(a0)
arx = np.concatenate((ar1,a0),axis=0)
arx

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [ 8,  9, 10]])