In [25]:
import datetime as dt

start = input("Enter the start date")
start = dt.datetime.strptime(start, '%Y-%m-%d')
end = input("Enter the start date")
end = dt.datetime.strptime(end, '%Y-%m-%d')
# print(end)
days_ct = 0

st = start
while(st<=end):
    # print(st.weekday())
    if not (st.weekday() ==5 or st.weekday() ==6):
        days_ct+=1
    st += dt.timedelta(days=1)

start= start.strftime("%Y-%m-%d")
end= end.strftime("%Y-%m-%d")

print(f"Total number of working days between {start} and {end} are {days_ct}")


Total number of working days between 2012-12-12 and 2012-12-19 are 6


In [47]:
import numpy as np
# generating 2 matrices
matA = np.random.rand(3,3)
matB = np.random.rand(3,3)

mat_sum = matB + matA
mat_pro = matA * matB
dot = matA.dot(matB)
det = np.linalg.det(matA)

print(matA)
print(matB)
print(mat_sum)
print(mat_pro)
print(dot)
print(det)

try :
    # detB = np.linalg.det(matB)
    inv = np.linalg.inv(matB)
    print(inv)
except :
    print('Matrix B is non-invertible')



[[0.97552097 0.42738309 0.92748357]
 [0.2835223  0.96761322 0.65888643]
 [0.83997053 0.48646293 0.73090643]]
[[0.87860746 0.75612417 0.04300826]
 [0.63866751 0.93005198 0.53256141]
 [0.84165552 0.71081393 0.43541434]]
[[1.85412843 1.18350727 0.97049182]
 [0.92218982 1.8976652  1.19144783]
 [1.68162605 1.19727687 1.16632077]]
[[0.8571     0.32315469 0.03988945]
 [0.18107649 0.89993059 0.35089748]
 [0.70696583 0.34578463 0.31824714]]
[[1.91067736 1.79437172 0.67340285]
 [1.42164334 1.58265431 0.81439586]
 [1.66386387 1.60709631 0.6134442 ]]
-0.10069441060256444
[[ 0.19174718 -2.16870144  2.63362931]
 [ 1.23553592  2.51510315 -3.19829867]
 [-2.38765955  0.0861919   2.42708264]]


In [60]:
import pandas as pd
dict = {'Product': ['Apple','Banana','Orange','Apple','Banana'],
        'Qty' : [10,15,20,12,18]}

data = pd.DataFrame(dict)
print(data)

data_tot = data.groupby('Product').sum().reset_index()
print(data_tot)

data_mean = data.groupby('Product').mean().reset_index()
print(data_mean)

  Product  Qty
0   Apple   10
1  Banana   15
2  Orange   20
3   Apple   12
4  Banana   18


Product   Qty
0   Apple  11.0
1  Banana  16.5
2  Orange  20.0

In [123]:
from datetime import datetime
print(datetime.now())

2023-09-12 15:39:22.468108


In [122]:
import keyboard
from time import sleep

a = '''
ar= np.arange(1,9).reshape(2,4)
print(ar)

mat = ar.reshape(-1,1)
mat

'''

sleep(1.5)
keyboard.write(a)